// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Trace.proto

package orionproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Trace struct {
	TraceId              string   `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	TraceName            string   `protobuf:"bytes,2,opt,name=trace_name,json=traceName,proto3" json:"trace_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trace) Reset()         { *m = Trace{} }
func (m *Trace) String() string { return proto.CompactTextString(m) }
func (*Trace) ProtoMessage()    {}
func (*Trace) Descriptor() ([]byte, []int) {
	return fileDescriptor_Trace_b02e5079415d281f, []int{0}
}
func (m *Trace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trace.Unmarshal(m, b)
}
func (m *Trace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trace.Marshal(b, m, deterministic)
}
func (dst *Trace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trace.Merge(dst, src)
}
func (m *Trace) XXX_Size() int {
	return xxx_messageInfo_Trace.Size(m)
}
func (m *Trace) XXX_DiscardUnknown() {
	xxx_messageInfo_Trace.DiscardUnknown(m)
}

var xxx_messageInfo_Trace proto.InternalMessageInfo

func (m *Trace) GetTraceId() string {
	if m != nil {
		return m.TraceId
	}
	return ""
}

func (m *Trace) GetTraceName() string {
	if m != nil {
		return m.TraceName
	}
	return ""
}

func init() {
	proto.RegisterType((*Trace)(nil), "com.thapovan.orion.proto.Trace")
}

func init() { proto.RegisterFile("Trace.proto", fileDescriptor_Trace_b02e5079415d281f) }

var fileDescriptor_Trace_b02e5079415d281f = []byte{
	// 122 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0e, 0x29, 0x4a, 0x4c,
	0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0x48, 0xce, 0xcf, 0xd5, 0x2b, 0xc9, 0x48,
	0x2c, 0xc8, 0x2f, 0x4b, 0xcc, 0xd3, 0xcb, 0x2f, 0xca, 0xcc, 0xcf, 0x83, 0xc8, 0x28, 0x39, 0x72,
	0xb1, 0x82, 0x15, 0x0a, 0x49, 0x72, 0x71, 0x94, 0x80, 0x18, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0xec, 0x60, 0xbe, 0x67, 0x8a, 0x90, 0x2c, 0x17, 0x17, 0x44, 0x2a, 0x2f,
	0x31, 0x37, 0x55, 0x82, 0x09, 0x2c, 0xc9, 0x09, 0x16, 0xf1, 0x4b, 0xcc, 0x4d, 0x75, 0xe2, 0x0b,
	0x60, 0x8c, 0xe2, 0x02, 0x9b, 0x09, 0x36, 0x32, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x30, 0x3d, 0x46, 0xcd, 0x82, 0x00, 0x00, 0x00,
}
